### ISSUE TITLE
Deprecation in Fastify vs module used by HttpIncoming

### ISSUE THREAD

**Issue by pearofducks** [podium-lib/issues#52]
https://github.com/watson/original-url/blob/master/index.js#L10

Fastify warns with: `[FST_LIGHTMYREQUEST_DEP01] FastifyDeprecationLightMyRequest: You are accessing "request.connection", use "request.socket" instead.`

Stack:
```
[FST_LIGHTMYREQUEST_DEP01] FastifyDeprecationLightMyRequest: You are accessing "request.connection", use "request.socket" instead.
    at Object.emit (/Users/pear/FINN/huck-server/node_modules/.pnpm/fastify-warning@0.2.0/node_modules/fastify-warning/index.js:52:13)
    at Request.get (/Users/pear/FINN/huck-server/node_modules/.pnpm/light-my-request@4.7.1/node_modules/light-my-request/lib/request.js:93:15)
    at module.exports (/Users/pear/FINN/huck-server/node_modules/.pnpm/original-url@1.2.3/node_modules/original-url/index.js:10:37)
    at urlFromRequest (/Users/pear/FINN/huck-server/node_modules/.pnpm/@podium+utils@4.4.34/node_modules/@podium/utils/lib/http-incoming.js:20:21)
    at new PodiumHttpIncoming (/Users/pear/FINN/huck-server/node_modules/.pnpm/@podium+utils@4.4.34/node_modules/@podium/utils/lib/http-incoming.js:29:21)
    at Object.<anonymous> (/Users/pear/FINN/huck-server/node_modules/.pnpm/@podium+fastify-layout@2.2.37/node_modules/@podium/fastify-layout/lib/layout-plugin.js:20:26)
    at hookIterator (/Users/pear/FINN/huck-server/node_modules/.pnpm/fastify@3.27.1/node_modules/fastify/lib/hooks.js:237:10)
    at next (/Users/pear/FINN/huck-server/node_modules/.pnpm/fastify@3.27.1/node_modules/fastify/lib/hooks.js:164:16)
    at hookRunner (/Users/pear/FINN/huck-server/node_modules/.pnpm/fastify@3.27.1/node_modules/fastify/lib/hooks.js:187:3)
    at preValidationCallback (/Users/pear/FINN/huck-server/node_modules/.pnpm/fastify@3.27.1/node_modules/fastify/lib/handleRequest.js:101:5)
```

**Comment by trygve-lie** [comment]
There are good reasons to make a clone of original-url and maintain this our self. The task here is then to make a fork of original-url package and fix this issue in our own fork. 

I would prefer if we also converted it to ESM and kept it on the v5 release only.
